apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebapp
        image: 169634835941.dkr.ecr.us-east-1.amazonaws.com/commonrepo:latest
        ports:
        - containerPort: 8080
