
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp
  labels:
    app: javawebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebapp
        image: 169634835941.dkr.ecr.us-east-1.amazonaws.com/commonrepo:${BUILD_TAG}
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: javawebapp
  labels:
    app: javawebapp
spec:
  selector:
    app: javawebapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: javawebapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: javawebapp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: javawebapp
            port:
              number: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
